---
title: "`r params$set_title`"
author: "`r params$set_author`"
date: "`r Sys.Date()`"
output:
  word_document:
    reference_docx: "MR_word_template.docx"
  bookdown::html_document2: default
  bookdown::word_document2: default
  pdf_document: default
  html_document: default
  bookdown::pdf_document2: default
params:
  printcode: no
  printwarning: no
  storecache: yes
  set_title: "Lebanon Year 1 (2016-2017) Measurement Report"
  set_author: "Michael Wu"
editor_options:
  chunk_output_type: console
always_allow_html: true
---

```{r setup, include=FALSE}
# set up knitr options
knitr::opts_chunk$set(echo = params$printcode, 
                      warning = params$printwarning, 
                      cache = params$storecache,
                      message = F, 
                      results="asis")

# load or install packages
# install_load <- function (package1, ...)  {   
# 
#    # convert arguments to vector
#    packages <- c(package1, ...)
# 
#    # start loop to determine if each package is installed
#    for(package in packages){
# 
#        # if package is installed locally, load
#        if(package %in% rownames(installed.packages()))
#           do.call('library', list(package))
# 
#        # if package is not installed locally, download, then load
#        else {
#           install.packages(package)
#           do.call("library", list(package))
#        }
#    } 
# }
#
#install_load("tidyverse", "psych", "MplusAutomation", "gridExtra", "semPlot", "kableExtra")

library(tidyverse)
library(psych)
library(MplusAutomation)
library(gridExtra)
library(semPlot)
library(kableExtra)
library(flextable)

knitr::read_chunk(here::here("R"),"functions.R")
```

```{r user input text}
year <- "Lebanon Year 1 (2016-2017)"

```

```{r user input data}
data_file_path <- "~/Box/3EA Analysis/3EA Lebanon_Analysis/Lebanon_Y1_FA/LBY1_PREIMPUTED_FULL_SPREAD_10-31-2019_mplus.dta"

subset_data <- Hmisc::Cs(
                HB1_AB_1, HB2_AB_1, HB3_AB_1, HB4_AB_1, HB5_AB_1, HB6_AB_1, 
                HB1_AD_1, HB2_AD_1, HB3_AD_1, HB4_AD_1, HB5_AD_1, HB6_AD_1, 
                HB1_SD_1, HB2_SD_1, HB3_SD_1, HB4_SD_1, HB5_SD_1, HB6_SD_1, 
                HB1_AR_1, HB2_AR_1, HB3_AR_1, HB4_AR_1, HB5_AR_1, HB6_AR_1, 
                
                HB1_AB_2, HB2_AB_2, HB3_AB_2, HB4_AB_2, HB5_AB_2, HB6_AB_2, 
                HB1_AD_2, HB2_AD_2, HB3_AD_2, HB4_AD_2, HB5_AD_2, HB6_AD_2, 
                HB1_SD_2, HB2_SD_2, HB3_SD_2, HB4_SD_2, HB5_SD_2, HB6_SD_2, 
                HB1_AR_2, HB2_AR_2, HB3_AR_2, HB4_AR_2, HB5_AR_2, HB6_AR_2,
                
                HB1_AB_3, HB2_AB_3, HB3_AB_3, HB4_AB_3, HB5_AB_3, HB6_AB_3, 
                HB1_AD_3, HB2_AD_3, HB3_AD_3, HB4_AD_3, HB5_AD_3, HB6_AD_3, 
                HB1_SD_3, HB2_SD_3, HB3_SD_3, HB4_SD_3, HB5_SD_3, HB6_SD_3, 
                HB1_AR_3, HB2_AR_3, HB3_AR_3, HB4_AR_3, HB5_AR_3, HB6_AR_3)


```

```{r data preparation, include = F}
dat <- haven::read_dta(data_file_path)

dat.s <- as.data.frame(select(dat, all_of(subset_data)))
```


# Data and Sample

This report presents descriptive and psychometric information of the measures used for `r year`.

# Method

# Results

## Descriptive Statistics

see Table \@ref(tab:descriptive).

```{r descriptive}
ds <- round(describe(dat.s), 3)

flextable(ds) %>%
  align(part = "all") %>% # left align
  set_caption(caption = "Descriptive Statistics") %>% 
  font(fontname = "Times", part = "all") %>% 
  fontsize(size = 10, part = "body") %>% 
  # add footer if you want
  # add_footer_row(values = "* p < 0.05. ** p < 0.01. *** p < 0.001.", 
  #                colwidths = 4) %>% 
  theme_booktabs() %>% # default theme
  autofit()


```

```{r ds_plot, fig.cap = c("p1","p2","p3"), fig.height = 8, fig.width = 12}

# descriptive plots

par(mfrow = c(4,6))

if(ncol(dat.s) <= 24){
  
  for (i in 1:ncol(dat.s)) {
    hist(dat.s[,i], main = "", xlab = names(dat.s)[i])}

  } else if(ncol(dat.s) <= 48) {
    
  for (i in 1:24) {
  hist(dat.s[,i], main = "", xlab = names(dat.s)[i])}
    
  for (i in 25:ncol(dat.s)) {
  hist(dat.s[,i], main = "", xlab = names(dat.s)[i])}
    
  } else if(ncol(dat.s) <= 72) {
    
  for (i in 1:24) {
  hist(dat.s[,i], main = "", xlab = names(dat.s)[i])}
    
  for (i in 25:48) {
  hist(dat.s[,i], main = "", xlab = names(dat.s)[i])}
    
  for (i in 49:ncol(dat.s)) {
  hist(dat.s[,i], main = "", xlab = names(dat.s)[i])}
    
  } else if(ncol(dat.s) <= 96) {
    
  for (i in 1:24) {
  hist(dat.s[,i], main = "", xlab = names(dat.s)[i])}
    
  for (i in 25:48) {
  hist(dat.s[,i], main = "", xlab = names(dat.s)[i])}
    
  for (i in 49:72) {
  hist(dat.s[,i], main = "", xlab = names(dat.s)[i])}
    
  for (i in 73:ncol(dat.s)) {
  hist(dat.s[,i], main = "", xlab = names(dat.s)[i])}
    
}
    
    



  
```
