---
title: "parent"
author: "Michael Wu"
date: "11/18/2020"
output: html_document
---
```{r function}

# function to render report
render_report = function(template, index, title) {
  rmarkdown::render(
    "child.Rmd", params = list(
      template = template,
      set_title = title
    ),
    envir = globalenv(),
    output_file = paste0("Report_", index, ".docx")
  )
}

```


```{r knit one report_quick knit}
render_report(template = "Template/input_template_lebanon_cs.xlsx",
              index = "lebanon_cs",
              title = "Lebanon Year 1 (2016-2017)")
```

```{r knit one report_manually set parameters}
rmarkdown::render("child.Rmd", params = "ask") 
```


```{r knit multiple reports separately}
# get input template file names
input_templates <- paste0("Template/",list.files("Template", pattern = "\\.xlsx$"))

# get measure names
index <- gsub("(Template/input_template_)(.*)(\\.xlsx)$", "\\2", input_templates)

# get document titles
title <- c()
for(i in 1:length(input_templates)){
  title[i] <- openxlsx::read.xlsx(input_templates[i], sheet = 1)$year
}


# rendering the Rmd document in a new R session so that objects in the current R session will not pollute the Rmd document

for (i in 1:length(input_templates)) {
  
  xfun::Rscript_call(
    rmarkdown::render,
    list(input =  "child.Rmd", 
        params = list(
        template = input_templates[i],
        set_title = title[i]
      ),
      output_file = paste0("Report_", index[i], ".docx")
    )
  )
  
}

```